### ISSUE TITLE
theoretical question

### ISSUE THREAD

**Issue by hlsafin** [ml-jku/helm#1]
Just a theoretical question here, but how does this do on Montezuma's Revenge? Is memory not an issue but exploration is for HELM?

**Comment by paischer101** [comment]
Thanks for the question!
HELM was designed for for abstract history representation in POMDPs, not for improving the exploratory behavior of the agent. 
We have not observed any improved exploratory behavior in our experiments.
Games such as Montezuma's Revenge heavily depend on exploration, so I assume you would need to augment HELM with an exploration component (such as GoExplore, ICM, RND, NovelD, RIDE, etc.) to explicitly enforce exploration.

**Comment by hlsafin** [comment]
So maybe I misunderstood something because I thought there is a similarity between games like mini-grid "keycorridor" where you have very sparse rewards setup and games like Montezuma's Revenge, no?
Thank you!

**Comment by paischer101** [comment]
I see what you are getting at.
Although the selected Minigrid environments provide sparse reward settings, they are still of a size such that a random agent receives some reward by chance.
We have not investigated the effect of HELM in larger environments with sparse rewards where a random agent does not receive any reward, but this would be very interesting to explore.

**Comment by hlsafin** [comment]
The thing is when I train this on MR for 6 million steps, it still gets rewards here and there (reaches 4 as the highest), but it never propagates and never truly learns how it got those rewards.

**Comment by paischer101** [comment]
Given that the state space of MR is much larger and more complex than our Minigrid examples, I'd assume it requires longer training.
Taking our Procgen experiments as an example, we trained for 25M steps and the model did not fully converge.
Also, our hyperparameters were tuned for each environment separately, thus, the default parameters might not be optimal for MR.

**Comment by hlsafin** [comment]
Thank you for the explanation!
