### ISSUE TITLE
The support for the other baseline models

### ISSUE THREAD

**Issue by HonoMi** [ml-jku/helm#2]
Hi,

Thanks for the nice repo.
We are working with the repo and found that the baseline models are cut-off as:
https://github.com/ml-jku/helm/blob/9970dac18dcda25ba38c471762d6cdc68178fee7/experiment.py#L38

Is it possible to share the codes for the baseline models ?

**Comment by paischer101** [comment]
Hi,
Thank you for your interest in our work.
I will add the support for our baselines in the next few days.

**Comment by paischer101** [comment]
The code now supports the Impala-PPO and CNN-PPO baselines as mentioned in the paper.
Simply specify 'CNN-PPO' or 'Impala-PPO' as model in the config.json file.
