### ISSUE TITLE
setting the seed

### ISSUE THREAD

**Issue by k-hyunji** [ml-jku/helm#6]
Hi! thank you for your great work!

I was testing out your codes and realized that you guys set the random seed as 0 for default.

My question is that even though I ran the code under the exactly same setting (seed default as 0), the test results were different for randommaze and keycorridor. 

Is this because of the nature of these environments? If not, what would be the reason? 

Thank you.

**Comment by paischer101** [comment]
Hi, thank you for your interest in our work!

We will upload the list of seeds for reproducing our runs in the next commit.
Also please note, that differences in hardware (GPU/CPU) can already lead to different results.
We ran most of our experiments on an A100 GPU and an AMD EPYC 7742 64-core processor.

**Comment by paischer101** [comment]
I just pushed a pickle file containing the 30 seeds we used for training our methods in the paper on MiniGrid and RandomMaze environments.
